sudo: false
language: python
python:
  - 2.7

install:
  - pip install coveralls coverage
  - pip install -r requirements.txt
  - python setup.py bdist_egg

script: nosetests

after_script: coveralls
