sudo: false
language: python
python:
  - 2.7
  - 3.6
env:
  - SVN_ROOT=https://dummy GIT_SSH_ROOT=ssh://git@dummy GIT_ROOT_DIR=controlstest

install:
  - pip install coveralls coverage
  - pip install -r requirements.txt
  - python setup.py bdist_egg

script:
  - python setup.py test
  - python setup.py build_sphinx


after_script: coveralls
